/*--------------------------------------------------------------------
ConfigStatus.cxx

ConfigStatus is meant to be a container for all settings  that were made in the config file.

created by Edgar Kellermann (edgar.kellermann@cern.ch)
--------------------------------------------------------------------*/

#include <JetTriggerPerformancePackage/ConfigStatus.h>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <iomanip>



ConfigStatus::ConfigStatus(bool a_debug,
			   bool a_debugInExecute,
			   std::string a_TriggerName,
			   bool a_isData,
			   bool a_checkLArError,
			   bool a_doOfflineJetKinematics,
			   bool a_doTriggerJetKinematics,
			   bool a_doTruthJetKinematics,
			   bool a_doLeadSubleadThirdJetKinematics,
			   bool a_doNthJetKinematics,
			   bool a_doKinematicsInBinsOfEta,
			   bool a_doEtainBinsOfPt,
               bool a_doMjj,
               bool a_doM23,
			   bool a_doyStar,
			   bool a_doDeltaPhi,
			   bool a_doPTBalance,
               bool a_doHT,
			   bool a_doMHT,
			   bool a_doMHTPhi,
			   bool a_doEMFrac,
			   bool a_doHECFrac,
			   bool a_doFracSamplingMax,
               bool a_calculateMjj,
               bool a_calculateM23,
               bool a_calculateYStar,
               bool a_doMatching,
			   bool a_doOfflineTruthResponse,
			   bool a_doTriggerTruthResponse,
			   bool a_doTriggerOfflineResponse,
			   bool a_doMjjResponseTrigVsOff,
			   bool a_doMjjResponseOffVsTruth,
			   bool a_doMjjResponseTrigVsTruth,
               int  a_Response_BinNumbers,
               float a_Response_MinBin,
               float a_Response_MaxBin,
               std::string a_PtResponse_ptBinning,
               std::string a_PtResponse_etaBinning,
               std::string a_MjjResponse_mjjBinning,
               std::string a_MjjResponse_etaBinning,
			   bool a_doTurnOns,
               std::string a_TurnOnName,
			   bool a_useTriggerDecisionTool,
			   bool a_useEmulation,
			   bool a_useTriggerBeforePraescale,
               int   a_PtTurnon_BinNumbers,
               float a_PtTurnon_MinBin,
               float a_PtTurnon_MaxBin,
               int   a_HtTurnon_BinNumbers,
               float a_HtTurnon_MinBin,
               float a_HtTurnon_MaxBin,
               int   a_TLATurnon_BinNumbers,
               float a_TLATurnon_MinBin,
               float a_TLATurnon_MaxBin,
               float a_HLT_cen_etaMin,
               float a_HLT_cen_etaMax,
               float a_HLT_fwd_etaMin,
               float a_HLT_fwd_etaMax,
               float a_L1_cen_etaMin,
               float a_L1_cen_etaMax,
               float a_L1_fwd_etaMin,
               float a_L1_fwd_etaMax,
               float a_TurnonCut_Timing,
			   bool a_doCuts,
               std::string a_cutStringKinematics,
               std::string a_cutStringTurnons,
			   bool a_doCleaning,
			   int a_doOnlyThisNumberOfEvents):
    debug(a_debug),
    debugInExecute(a_debugInExecute),
    TriggerName(a_TriggerName),
    isData(a_isData),
    checkLArError(a_checkLArError),
    doOfflineJetKinematics(a_doOfflineJetKinematics),
    doTriggerJetKinematics(a_doTriggerJetKinematics),
    doTruthJetKinematics(a_doTruthJetKinematics),
    doLeadSubleadThirdJetKinematics(a_doLeadSubleadThirdJetKinematics),
    doNthJetKinematics(a_doNthJetKinematics),
    doKinematicsInBinsOfEta(a_doKinematicsInBinsOfEta),
    doEtainBinsOfPt(a_doEtainBinsOfPt),
    doyStar(a_doyStar),
    doDeltaPhi(a_doDeltaPhi),
    doPTBalance(a_doPTBalance),
    doMjj(a_doMjj),
    doM23(a_doM23),
    doHT(a_doHT),
    doMHT(a_doMHT),
    doMHTPhi(a_doMHTPhi),
    doEMFrac(a_doEMFrac),
    doHECFrac(a_doHECFrac),
    doFracSamplingMax(a_doFracSamplingMax),
    calculateMjj(a_calculateMjj),
    calculateM23(a_calculateM23),
    calculateYStar(a_calculateYStar),
    doMatching(a_doMatching),
    doOfflineTruthResponse(a_doOfflineTruthResponse),
    doTriggerTruthResponse(a_doTriggerTruthResponse),
    doTriggerOfflineResponse(a_doTriggerOfflineResponse),
    doMjjResponseTrigVsOff(a_doMjjResponseTrigVsOff),
    doMjjResponseOffVsTruth(a_doMjjResponseOffVsTruth),
    doMjjResponseTrigVsTruth(a_doMjjResponseTrigVsTruth),
    Response_BinNumbers(a_Response_BinNumbers),
    Response_MaxBin(a_Response_MaxBin),
    Response_MinBin(a_Response_MinBin),
    PtResponse_ptBinning(a_PtResponse_ptBinning),
    PtResponse_etaBinning(a_PtResponse_etaBinning),
    MjjResponse_mjjBinning(a_MjjResponse_mjjBinning),
    MjjResponse_etaBinning(a_MjjResponse_etaBinning),
    HLT_cen_etaMin(a_HLT_cen_etaMin),
    HLT_cen_etaMax(a_HLT_cen_etaMax),
    HLT_fwd_etaMin(a_HLT_fwd_etaMin),
    HLT_fwd_etaMax(a_HLT_fwd_etaMax),
    L1_cen_etaMin(a_L1_cen_etaMin),
    L1_cen_etaMax(a_L1_cen_etaMax),
    L1_fwd_etaMin(a_L1_fwd_etaMin),
    L1_fwd_etaMax(a_L1_fwd_etaMax),
    TurnonCut_Timing(a_TurnonCut_Timing),
    doCuts(a_doCuts),
    cutStringKinematics(a_cutStringKinematics),
    cutStringTurnons(a_cutStringTurnons),
    doCleaning(a_doCleaning),
    doOnlyThisNumberOfEvents(a_doOnlyThisNumberOfEvents),
    doTurnOns(a_doTurnOns),
    TurnOnName(a_TurnOnName),
    useTriggerDecisionTool(a_useTriggerDecisionTool),
    useEmulation(a_useEmulation),
    useTriggerBeforePraescale(a_useTriggerBeforePraescale),
    PtTurnon_BinNumbers(a_PtTurnon_BinNumbers),
    PtTurnon_MinBin(a_PtTurnon_MinBin),
    PtTurnon_MaxBin(a_PtTurnon_MaxBin),
    HtTurnon_BinNumbers(a_HtTurnon_BinNumbers),
    HtTurnon_MinBin(a_HtTurnon_MinBin),
    HtTurnon_MaxBin(a_HtTurnon_MaxBin),
    TLATurnon_BinNumbers(a_TLATurnon_BinNumbers),
    TLATurnon_MinBin(a_TLATurnon_MinBin),
    TLATurnon_MaxBin(a_TLATurnon_MaxBin)
{
  if (m_debug) std::cout << "Starting constructor ConfigStatus()..." << std::endl;
}

ConfigStatus::~ConfigStatus()
{
  if (m_debug) std::cout << "Starting destructor ConfigStatus()..." << std::endl;
}
